'------------------------------------------------------------------------------
' <auto-generated>
'     Ten kod został wygenerowany przez narzędzie.
'     Wersja wykonawcza:4.0.30319.42000
'
'     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
'     kod zostanie ponownie wygenerowany.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    'przez narzędzie, takie jak ResGen lub Visual Studio.
    'Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    'z opcją /str lub ponownie utwórz projekt VS.
    '''<summary>
    '''  Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ACAM.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        '''  przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property large1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("large1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property large2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("large2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property large3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("large3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property large4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("large4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property large5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("large5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property large6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("large6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property large7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("large7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property large8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("large8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property large9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("large9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
